# FROM openjdk:17-jdk-slim

# WORKDIR /app

# COPY ShapeAreaCalculator.java /app/

# RUN javac ShapeAreaCalculator.java

# CMD ["java", "ShapeAreaCalculator"]

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY *.java /app/

RUN javac *.java